version: "3.1"

services:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
  app:
    image: 127.0.0.1:5000/student_api
    ports:
      - 1980:8000
    build: app
    environment:
      MONGO_HOST: mongo
 
