version: "3.1"

services:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
  app:
    image: student_api
    ports:
      - 1980:8000
    build: app
    environment:
      MONGO_HOST: mongo
 
